/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"



/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	SC_GPIO_Init();
	SC_OPTION_Init();
	SC_RCC_Init();
	SC_SYSTICK_Init();
	SC_UART5_Init();
	SC_ADC_Init();
	SC_OP_Init();
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_Unlock(0xFF);
	RCC_HXTCmd(DISABLE);
	RCC_LXTCmd(DISABLE);
	RCC_LIRCCmd(ENABLE);
	RCC_HIRCCmd(ENABLE);
	/*INTEN*/RCC_ITConfig(ENABLE);
	RCC_HIRCDIV1Cmd(DISABLE);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HIRC_2);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_APB0Config(RCC_HCLK_Div1);
	RCC_APB0Cmd(ENABLE);
	RCC_APB2Config(RCC_HCLK_Div1);
	RCC_APB2Cmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_Unlock(0xFF);
	RCC_SystickCLKConfig(RCC_SysTickSource_HCLK_DIV8);
	RCC_SystickSetCounter(16000);
	NVIC_SetPriority(SysTick_IRQn,0);
	RCC_SystickCmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    /*GPIOInit_PA10 Struct*/GPIO_InitTypeDef GPIOInit_PA10_Struct;
    GPIOInit_PA10_Struct.GPIO_Pin = GPIO_Pin_10;
    GPIOInit_PA10_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PA10_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOA,&GPIOInit_PA10_Struct);/*TK4端口初始化*/
    /*GPIOInit_PA11 Struct*/GPIO_InitTypeDef GPIOInit_PA11_Struct;
    GPIOInit_PA11_Struct.GPIO_Pin = GPIO_Pin_11;
    GPIOInit_PA11_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PA11_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOA,&GPIOInit_PA11_Struct);/*TK5端口初始化*/
    /*GPIOInit_PA12 Struct*/GPIO_InitTypeDef GPIOInit_PA12_Struct;
    GPIOInit_PA12_Struct.GPIO_Pin = GPIO_Pin_12;
    GPIOInit_PA12_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PA12_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOA,&GPIOInit_PA12_Struct);/*TK6端口初始化*/
    /*GPIOInit_PA13 Struct*/GPIO_InitTypeDef GPIOInit_PA13_Struct;
    GPIOInit_PA13_Struct.GPIO_Pin = GPIO_Pin_13;
    GPIOInit_PA13_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PA13_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOA,&GPIOInit_PA13_Struct);/*TK7端口初始化*/
	/*GPIOInit_PA06 Struct*/GPIO_InitTypeDef GPIOInit_PA06_Struct;
	GPIOInit_PA06_Struct.GPIO_Pin = GPIO_Pin_6;
	GPIOInit_PA06_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA06_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA06_Struct);/*PA.06端口初始化*/
	/*GPIOInit_PA07 Struct*/GPIO_InitTypeDef GPIOInit_PA07_Struct;
	GPIOInit_PA07_Struct.GPIO_Pin = GPIO_Pin_7;
	GPIOInit_PA07_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA07_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA07_Struct);/*PA.07端口初始化*/
	/*GPIOInit_PA08 Struct*/GPIO_InitTypeDef GPIOInit_PA08_Struct;
	GPIOInit_PA08_Struct.GPIO_Pin = GPIO_Pin_8;
	GPIOInit_PA08_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA08_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA08_Struct);/*PA.08端口初始化*/
	/*GPIOInit_PA09 Struct*/GPIO_InitTypeDef GPIOInit_PA09_Struct;
	GPIOInit_PA09_Struct.GPIO_Pin = GPIO_Pin_9;
	GPIOInit_PA09_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PA09_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA09_Struct);/*PA.09端口初始化*/
	/*GPIOInit_PB02 Struct*/GPIO_InitTypeDef GPIOInit_PB02_Struct;
	GPIOInit_PB02_Struct.GPIO_Pin = GPIO_Pin_2;
	GPIOInit_PB02_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB02_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB02_Struct);/*PB.02端口初始化*/
	/*GPIOInit_PB03 Struct*/GPIO_InitTypeDef GPIOInit_PB03_Struct;
	GPIOInit_PB03_Struct.GPIO_Pin = GPIO_Pin_3;
	GPIOInit_PB03_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB03_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB03_Struct);/*PB.03端口初始化*/
	/*GPIOInit_PB04 Struct*/GPIO_InitTypeDef GPIOInit_PB04_Struct;
	GPIOInit_PB04_Struct.GPIO_Pin = GPIO_Pin_4;
	GPIOInit_PB04_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB04_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB04_Struct);/*PB.04端口初始化*/
	/*GPIOInit_PB05 Struct*/GPIO_InitTypeDef GPIOInit_PB05_Struct;
	GPIOInit_PB05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PB05_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB05_Struct);/*PB.05端口初始化*/
	/*GPIOInit_PB06 Struct*/GPIO_InitTypeDef GPIOInit_PB06_Struct;
	GPIOInit_PB06_Struct.GPIO_Pin = GPIO_Pin_6;
	GPIOInit_PB06_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB06_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB06_Struct);/*PB.06端口初始化*/
	/*GPIOInit_PB07 Struct*/GPIO_InitTypeDef GPIOInit_PB07_Struct;
	GPIOInit_PB07_Struct.GPIO_Pin = GPIO_Pin_7;
	GPIOInit_PB07_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB07_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB07_Struct);/*PB.07端口初始化*/
	/*GPIOInit_PB08 Struct*/GPIO_InitTypeDef GPIOInit_PB08_Struct;
	GPIOInit_PB08_Struct.GPIO_Pin = GPIO_Pin_8;
	GPIOInit_PB08_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB08_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB08_Struct);/*PB.08端口初始化*/
	/*GPIOInit_PB09 Struct*/GPIO_InitTypeDef GPIOInit_PB09_Struct;
	GPIOInit_PB09_Struct.GPIO_Pin = GPIO_Pin_9;
	GPIOInit_PB09_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB09_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB09_Struct);/*PB.09端口初始化*/
	/*GPIOInit_PB10 Struct*/GPIO_InitTypeDef GPIOInit_PB10_Struct;
	GPIOInit_PB10_Struct.GPIO_Pin = GPIO_Pin_10;
	GPIOInit_PB10_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB10_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB10_Struct);/*PB.10端口初始化*/
	/*GPIOInit_PB13 Struct*/GPIO_InitTypeDef GPIOInit_PB13_Struct;
	GPIOInit_PB13_Struct.GPIO_Pin = GPIO_Pin_13;
	GPIOInit_PB13_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB13_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB13_Struct);/*PB.13端口初始化*/
	/*GPIOInit_PB14 Struct*/GPIO_InitTypeDef GPIOInit_PB14_Struct;
	GPIOInit_PB14_Struct.GPIO_Pin = GPIO_Pin_14;
	GPIOInit_PB14_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB14_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB14_Struct);/*PB.14端口初始化*/
	/*GPIOInit_PB15 Struct*/GPIO_InitTypeDef GPIOInit_PB15_Struct;
	GPIOInit_PB15_Struct.GPIO_Pin = GPIO_Pin_15;
	GPIOInit_PB15_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB15_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB15_Struct);/*PB.15端口初始化*/
	/*GPIOInit_PC9 Struct*/GPIO_InitTypeDef GPIOInit_PC9_Struct;
	GPIOInit_PC9_Struct.GPIO_Pin = GPIO_Pin_9;
	GPIOInit_PC9_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PC9_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC9_Struct);/*PB.15露丝诔玫始禄炉*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*GPIOInit_PC00 Struct*/GPIO_InitTypeDef GPIOInit_PC00_Struct;
	GPIOInit_PC00_Struct.GPIO_Pin = GPIO_Pin_0;
	GPIOInit_PC00_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC00_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC00_Struct);/*TxD5端口初始化*/
	/*GPIOInit_PC01 Struct*/GPIO_InitTypeDef GPIOInit_PC01_Struct;
	GPIOInit_PC01_Struct.GPIO_Pin = GPIO_Pin_1;
	GPIOInit_PC01_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC01_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC01_Struct);/*RxD5端口初始化*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_UART5, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 32000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode =  UART_Mode_10B;
	UART_Init(UART5, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART5,UART_IT_EN,DISABLE);
	/*Init Struct*/UART_PinRemapConfig(UART5,UART_PinRemap_Default);
	UART_TXCmd(UART5,ENABLE);
	UART_RXCmd(UART5,ENABLE);
	Printf_UartInit(UART5);
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*Init Struct*/ADC_InitTypeDef ADC_Base_InitStruct;
	ADC_Base_InitStruct.ADC_ConvMode = ADC_ConvMode_Continuous;
	ADC_Base_InitStruct.ADC_Prescaler = ADC_Prescaler_6CLOCK;
	ADC_Base_InitStruct.ADC_EAIN = ADC_EAIN_Less|ADC_EAIN_15;
	ADC_Base_InitStruct.ADC_VREF = ADC_VREF_2_048V;
	ADC_Init(ADC, &ADC_Base_InitStruct);
	ADC_SetChannel(ADC,ADC_Channel_15);
	/*ADCIF*/ADC_ITConfig(ADC,ADC_IT_ADCIF, ENABLE);
	ADC_DMACmd(ADC,DISABLE);
	/*Init Struct*/NVIC_SetPriority(ADC_IRQn,3);/*ADC*/
	NVIC_EnableIRQ(ADC_IRQn);
	ADC_Cmd(ADC,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief VREF init
  * @note 
  * @param
  */
void SC_VREF_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DAC init
  * @note 
  * @param
  */
void SC_DAC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TemperSensor init
  * @note 
  * @param
  */
void SC_TemperSensor_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief PCAP init
  * @note 
  * @param
  */
void SC_PCAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief EPWM init
  * @note 
  * @param
  */
void SC_EPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}





/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*GPIOInit_PA03 Struct*/GPIO_InitTypeDef GPIOInit_PA03_Struct;
	GPIOInit_PA03_Struct.GPIO_Pin = GPIO_Pin_3;
	GPIOInit_PA03_Struct.GPIO_Mode = GPIO_Mode_IN_HI;
	GPIOInit_PA03_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA03_Struct);/*OP_P0端口初始化*/
	/*GPIOInit_PA04 Struct*/GPIO_InitTypeDef GPIOInit_PA04_Struct;
	GPIOInit_PA04_Struct.GPIO_Pin = GPIO_Pin_4;
	GPIOInit_PA04_Struct.GPIO_Mode = GPIO_Mode_IN_HI;
	GPIOInit_PA04_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA04_Struct);/*OP_N端口初始化*/
	/*GPIOInit_PA05 Struct*/GPIO_InitTypeDef GPIOInit_PA05_Struct;
	GPIOInit_PA05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PA05_Struct.GPIO_Mode = GPIO_Mode_IN_HI;
	GPIOInit_PA05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA05_Struct);/*OP_O端口初始化*/
	/*Init Struct*/OP_InitTypeDef OP_InitStruct;
	OP_InitStruct.OP_ShortCircuit = OP_ShortCircuit_OFF;
	OP_InitStruct.OP_FDBResisrance = OP_FDBResisrance_VSS;
	OP_InitStruct.OP_PGAGain = OP_PGAGain_NonInvert8_Invert7;
	OP_InitStruct.OP_Posittive = OP_Posittive_OPP0;
	OP_InitStruct.OP_Negative = OP_Negative_OPN;
	OP_InitStruct.OP_Output = OP_Output_ON;
	OP_Init(OP, &OP_InitStruct);
	OP_Cmd(OP,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief OP0 init
  * @note 
  * @param
  */
void SC_OP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}
/**
  * @brief OP1 init
  * @note 
  * @param
  */
void SC_OP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief OP2 init
  * @note 
  * @param
  */
void SC_OP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief QEP0 init
  * @note 
  * @param
  */
void SC_QEP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief QEP1 init
  * @note 
  * @param
  */
void SC_QEP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}




/**
  * @brief CAN init
  * @note 
  * @param
  */
void SC_CAN_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI3 init
  * @note
  * @param
  */
void SC_SPI3_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI2 init
  * @note
  * @param
  */
void SC_TWI2_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TWI3 init
  * @note
  * @param
  */
void SC_TWI3_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief LCD init
  * @note 
  * @param
  */

void SC_LCD_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC LED Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief SC MR Init
  * @note 
  * @param
  */
void SC_MR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP Init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP0 Init
  * @note 
  * @param
  */
void SC_ACMP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP1 Init
  * @note 
  * @param
  */
void SC_ACMP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP2 Init
  * @note 
  * @param
  */
void SC_ACMP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP3 Init
  * @note 
  * @param
  */
void SC_ACMP3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC QSPI0 Init
  * @note
  * @param
  */
void SC_QSPI0_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief SC QSPI1 Init
  * @note
  * @param
  */
void SC_QSPI1_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
